# Generated by Django 5.2.4 on 2025-07-05 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10)),
                ('word_count', models.PositiveIntegerField()),
                ('character_count', models.PositiveIntegerField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'text_content',
                'indexes': [models.Index(fields=['difficulty', 'is_active'], name='text_conten_difficu_ee0df8_idx'), models.Index(fields=['word_count'], name='text_conten_word_co_2e404b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(choices=[(15, '15 seconds'), (30, '30 seconds'), (60, '1 minute')], db_index=True)),
                ('text_content', models.TextField()),
                ('typed_text', models.TextField()),
                ('wpm', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('typing_time', models.FloatField(help_text='Actual time taken in seconds')),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('correct_chars', models.PositiveIntegerField(default=0)),
                ('incorrect_chars', models.PositiveIntegerField(default=0)),
                ('total_chars', models.PositiveIntegerField(default=0)),
                ('focus_lost_count', models.PositiveIntegerField(default=0)),
                ('suspicious_events', models.JSONField(blank=True, default=list)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'typing_test_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='typing_test_user_id_cdb7b3_idx'), models.Index(fields=['duration', '-wpm'], name='typing_test_duratio_db6be5_idx'), models.Index(fields=['completed', '-started_at'], name='typing_test_complet_ddcb5f_idx'), models.Index(fields=['-wpm'], name='typing_test_wpm_575494_idx'), models.Index(fields=['user', 'duration', '-wpm'], name='typing_test_user_id_41af2a_idx'), models.Index(fields=['session_key'], name='typing_test_session_0cb455_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('completed_tests', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('best_wpm_15s', models.FloatField(blank=True, db_index=True, null=True)),
                ('best_wpm_30s', models.FloatField(blank=True, db_index=True, null=True)),
                ('best_wpm_60s', models.FloatField(blank=True, db_index=True, null=True)),
                ('best_accuracy_15s', models.FloatField(blank=True, null=True)),
                ('best_accuracy_30s', models.FloatField(blank=True, null=True)),
                ('best_accuracy_60s', models.FloatField(blank=True, null=True)),
                ('avg_wpm', models.FloatField(db_index=True, default=0.0)),
                ('avg_accuracy', models.FloatField(default=0.0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_time_typed', models.PositiveIntegerField(default=0)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stats',
                'indexes': [models.Index(fields=['-best_wpm_15s'], name='user_stats_best_wp_188ba0_idx'), models.Index(fields=['-best_wpm_30s'], name='user_stats_best_wp_337bb7_idx'), models.Index(fields=['-best_wpm_60s'], name='user_stats_best_wp_0854fb_idx'), models.Index(fields=['-avg_wpm'], name='user_stats_avg_wpm_944d28_idx'), models.Index(fields=['-completion_rate'], name='user_stats_complet_e48099_idx'), models.Index(fields=['last_test_at'], name='user_stats_last_te_31ff60_idx')],
            },
        ),
    ]
