# Generated by Django 5.2.4 on 2025-07-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typing_test', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(choices=[(15, '15 seconds'), (30, '30 seconds'), (60, '1 minute')], db_index=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], db_index=True, max_length=10)),
                ('wpm', models.FloatField(db_index=True)),
                ('accuracy', models.FloatField()),
                ('composite_score', models.FloatField(db_index=True)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('total_entries', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typing_test.testsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['duration', 'period', '-composite_score'], name='leaderboard_duratio_89dc6f_idx'), models.Index(fields=['period_start', 'period_end'], name='leaderboard_period__97ebdc_idx'), models.Index(fields=['-wpm'], name='leaderboard_wpm_ac3f49_idx'), models.Index(fields=['rank'], name='leaderboard_rank_db2e62_idx')],
                'unique_together': {('user', 'duration', 'period', 'period_start')},
            },
        ),
    ]
